# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56b59b96141c697896f8062c1fa7675324e28ffb9f2d7443acba1e311d1351c8e236562715c577c67df5d07a25c7be55398abb1c27c3a5d3ea29a701ce91077d

test:
  secret_key_base: 2e9680fcdf3eca76d9b60d0aa3e4d8891918b4ba9cafbbed99aa0d99eb0482d0c39620fdb697720c0864767e024117894030e99e176a7ff33b807574dfd28590

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
